#!/usr/bin/ruby
#
# Copyright (c) Arun Viswanathan 2008 (aviswana@ieee.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################

require 'net/http'

from = ARGV[0] 
to = ARGV[1]

# Sanity !
if (ARGV.length != 2) 
   puts "\n"
   puts "Currency Conversion "
   puts "+=+=+=+=+=+=+=+=+=+="
   puts "Copyright (c) Arun Viswanathan 2008"
   puts "\n"
   puts "Usage: ./convert.rb <from> <to>\n"
   puts "where"
   puts "       from : from currency Code"
   puts "       to   : to currency Codes"
   puts "Currency codes"
   puts "=============="
   puts "Britain (United Kingdom), Pound (GBP)"
   puts "British Indian Ocean Territory, United Kingdom Pound (GBP)"
   puts "British Indian Ocean Territory, United States Dollar (USD)"
   puts "British Virgin Islands, United States Dollar (USD)"
   puts "Brunei, Dollar (BND)"
   puts "Brunei, Singapore Dollar (SGD)"
   puts "Bulgaria, Lev (BGN)"
   puts "Burkina Faso, CFA Franc BCEAO (XOF)"
   puts "Burma (Myanmar), Kyat (MMK)"
   puts "Burundi, Franc (BIF)"
   puts ""
   puts "Cambodia, Riel (KHR)"
   puts "Cameroon, CFA Franc BEAC (XAF)"
   puts "Canada, Dollar (CAD)"
   puts "Canary Islands, Euro (EUR)"
   puts "Cape Verde, Escudo (CVE)"
   puts "Cayman Islands, Dollar (KYD)"
   puts "Central African Republic, CFA Franc BEAC (XAF)"
   puts "CFA Communauté Financière Africaine BEAC Franc (XAF)"
   puts "CFA Communauté Financière Africaine BCEAO Franc (XOF)"
   puts "Chad, CFA Franc BEAC (XAF)"
   puts "Chile, Peso (CLP)"
   puts "China, Yuan Renminbi (CNY)"
   puts "Christmas Island, Australia Dollar (AUD)"
   puts "Cocos (Keeling Islands, Australia Dollar (AUD)"
   puts "Colombia, Peso (COP)"
   puts "Communauté Financière Africaine BEAC Franc (XAF)"
   puts "Communauté Financière Africaine BCEAO Franc (XOF)"
   puts "Comoros, Franc (KMF)"
   puts "Comptoirs Français du Pacifique Franc (XPF)"
   puts "Congo/Brazzaville, CFA Franc BEAC (XAF)"
   puts "Congo/Kinshasa, Franc (CDF)"
   puts "Cook Islands, New Zealand Dollar (NZD)"
   puts "Coral Sea Islands, Australia Dollar (AUD)"
   puts "Costa Rica, Colon (CRC)"
   puts "Côte d'Ivoire, CFA Franc BCEAO (XOF)"
   puts "Croatia, Kuna (HRK)"
   puts "Cuba, Convertible Peso (CUC)"
   puts "Cuba, Peso (CUP)"
   puts "Curaço, Netherlands Antilles Guilder (ANG)"
   puts "Cyprus, Euro (EUR)"
   puts "Czech Republic, Koruna (CZK)"
   puts ""
   puts "Denmark, Krone (DKK)"
   puts "Djibouti, Franc (DJF)"
   puts "Dominica, East Caribbean Dollar (XCD)"
   puts "Dominican Republic, Peso (DOP)"
   puts "Dutch (Netherlands), Euro (EUR)"
   puts ""
   puts "East Caribbean Dollar (XCD)"
   puts "East Timor, United States Dollar (USD)"
   puts "Ecuador, United States Dollar (USD)"
   puts "Egypt, Pound (EGP)"
   puts "El Salvador, Colon (SVC)"
   puts "El Salvador, United States Dollar (USD)"
   puts "England (United Kingdom), Pound (GBP)"
   puts "Equatorial Guinea, CFA Franc BEAC (XAF)"
   puts "Eritrea, Nakfa (ERN)"
   puts "Estonia, Kroon (EEK)"
   puts "Ethiopia, Birr (ETB)"
   puts "Euro (EUR)"
   puts "Europa Island, Euro (EUR)"
   puts ""
   puts "Falkland Islands, Pound (FKP)"
   puts "Faroe Islands, Denmark Krone (DKK)"
   puts "Fiji, Dollar (FJD)"
   puts "Finland, Euro (EUR)"
   puts "France, Euro (EUR)"
   puts "French Guiana, Euro (EUR)"
   puts "French Polynesia, Comptoirs Français du Pacifique Franc (XPF)"
   puts "French Polynesia, Euro (EUR)"
   puts "French Southern and Antarctic Lands, Euro (EUR)"
   puts ""
   puts "Gabon, CFA Franc BEAC (XAF)"
   puts "Gambia, Dalasi (GMD)"
   puts "Gaza Strip, Israel New Shekel (ILS)"
   puts "Georgia, Lari (GEL)"
   puts "Germany, Euro (EUR)"
   puts "Ghana, Cedi (GHS)"
   puts "Gibraltar, Pound (GIP)"
   puts "Gold Ounce (XAU)"
   puts "Great Britain (United Kingdom), Pound (GBP)"
   puts "Greece, Euro (EUR)"
   puts "Greenland, Denmark Krone (DKK)"
   puts "Grenada, East Caribbean Dollar (XCD)"
   puts "Guadeloupe, Euro (EUR)"
   puts "Guam, United States Dollar (USD)"
   puts "Guatemala, Quetzal (GTQ)"
   puts "Guernsey, Pound (GGP)"
   puts "Guinea, Franc (GNF)"
   puts "Guinea-Bissau, CFA Franc BCEAO (XOF)"
   puts "Guyana, Dollar (GYD)"
   puts ""
   puts "Haiti, Gourde (HTG)"
   puts "Holland (Netherlands), Euro (EUR)"
   puts "Holy See (Vatican City), Euro (EUR)"
   puts "Honduras, Lempira (HNL)"
   puts "Hong Kong, Dollar (HKD)"
   puts "Hungary, Forint (HUF)"
   puts ""
   puts "Iceland, Krona (ISK)"
   puts "India, Rupee (INR)"
   puts "Indonesia, Rupiah (IDR)"
   puts "International Monetary Fund Special Drawing Right (XDR)"
   puts "Iran, Rial (IRR)"
   puts "Iraq, Dinar (IQD)"
   puts "Ireland, Euro (EUR)"
   puts "Islas Malvinas (Falkland Islands), Pound (FKP)"
   puts "Isle of Man, Pound (IMP)"
   puts "Israel, New Shekel (ILS)"
   puts "Italy, Euro (EUR)"
   puts "Ivory Coast (Côte d'Ivoire), CFA Franc BCEAO (XOF)"
   puts "Jamaica, Dollar (JMD)"
   puts "Japan, Yen (JPY)"
   puts ""
   puts "Jersey, Pound (JEP)"
   puts "Johnson, United States Dollar (USD)"
   puts "Jordan, Dinar (JOD)"
   puts "Juan de Nova, Euro (EUR)"
   puts ""
   puts "Kazakhstan, Tenge (KZT)"
   puts "Kenya, Shilling (KES)"
   puts "Kiribati, Australia Dollar (AUD)"
   puts "Kuwait, Dinar (KWD)"
   puts "Kyrgyzstan, Som (KGS)"
   puts ""
   puts "Laos, Kip (LAK)"
   puts "Latvia, Lat (LVL)"
   puts "Lebanon, Pound (LBP)"
   puts "Lesotho, Loti (LSL)"
   puts "Liberia, Dollar (LRD)"
   puts "Libya, Dinar (LYD)"
   puts "Liechtenstein, Switzerland Franc (CHF)"
   puts "Lithuania, Litas (LTL)"
   puts "Luxembourg, Euro (EUR)"
   puts ""
   puts "Macau, Pataca (MOP)"
   puts "Macedonia, Denar (MKD)"
   puts "Madagascar, Ariary (MGA)"
   puts "Madeira Islands, Euro (EUR)"
   puts "Malawi, Kwacha (MWK)"
   puts "Malaysia, Ringgit (MYR)"
   puts "Maldives, Rufiyaa (MVR)"
   puts "Mali, CFA Franc BCEAO (XOF)"
   puts "Malta, Euro (EUR)"
   puts "Malvinas (Falkland Islands), Pound (FKP)"
   puts "Marshall Islands, United States Dollar (USD)"
   puts "Martinique, Euro (EUR)"
   puts "Mauritania, Ouguiya (MRO)"
   puts "Mauritius, Rupee (MUR)"
   puts "Mayotte, Euro (EUR)"
   puts "Mexico, Peso (MXN)"
   puts "Micronesia, United States Dollar (USD)"
   puts "Midway Islands, United States Dollar (USD)"
   puts "Moldova, Leu (MDL)"
   puts "Monaco, Euro (EUR)"
   puts "Mongolia, Tughrik (MNT)"
   puts "Montenegro, Euro (EUR)"
   puts "Montserrat, East Caribbean Dollar (XCD)"
   puts "Morocco, Dirham (MAD)"
   puts "Mozambique, Metical (MZN)"
   puts "Myanmar (Burma), Kyat (MMK)"
   puts ""
   puts "Namibia, Dollar (NAD)"
   puts "Nauru, Australia Dollar (AUD)"
   puts "Navassa, Haiti Gourde (HTG)"
   puts "Navassa, United States Dollar (USD)"
   puts "Nepal, Rupee (NPR)"
   puts "Netherlands Antilles, Guilder (ANG)"
   puts "Netherlands, Euro (EUR)"
   puts "New Caledonia, Comptoirs Français du Pacifique Franc (XPF)"
   puts "New Zealand, Dollar (NZD)"
   puts "Nicaragua, Cordoba (NIO)"
   puts "Niger, CFA Franc BCEAO (XOF)"
   puts "Nigeria, Naira (NGN)"
   puts "Niue, New Zealand Dollar (NZD)"
   puts "Norfolk Island, Australia Dollar (AUD)"
   puts "North Korea, Won (KPW)"
   puts "Northern Mariana Islands, United States Dollar (USD)"
   puts "Norway, Krone (NOK)"
   puts ""
   puts "Oman, Rial (OMR)"
   puts ""
   puts "Pakistan, Rupee (PKR)"
   puts "Palau, United States Dollar (USD)"
   puts "Palladium Ounce (XPD)"
   puts "Panama, Balboa (PAB)"
   puts "Panama, United States Dollar (USD)"
   puts "Papua New Guinea, Kina (PGK)"
   puts "Paracel Islands, China Yuan Renminbi (CNY)"
   puts "Paracel Islands, Vietnam Dong (VND)"
   puts "Paraguay, Guarani (PYG)"
   puts "Peru, Nuevo Sol (PEN)"
   puts "Philippines, Peso (PHP)"
   puts "Pitcairn, New Zealand Dollar (NZD)"
   puts "Platinum Ounce (XPT)"
   puts "Poland, Zloty (PLN)"
   puts "Portugal, Euro (EUR)"
   puts "Puerto Rico, United States Dollar (USD)"
   puts ""
   puts "Qatar, Riyal (QAR)"
   puts ""
   puts "Réunion, Euro (EUR)"
   puts "Romania, New Leu (RON)"
   puts "Russia, Ruble (RUB)"
   puts "Rwanda, Franc (RWF)"
   puts ""
   puts "Saba, Netherlands Antilles Guilder (ANG)"
   puts "Saint Helena, Pound (SHP)"
   puts "Saint Kitts and Nevis, East Caribbean Dollar (XCD)"
   puts "Saint Lucia, East Caribbean Dollar (XCD)"
   puts "Saint Pierre and Miquelon, Euro (EUR)"
   puts "Saint Vincent and The Grenadines, East Caribbean Dollar (XCD)"
   puts "Saint-Martin, Euro (EUR)"
   puts "Samoa, Tala (WST)"
   puts "San Marino, Euro (EUR)"
   puts "São Tome and Principe, Dobra (STD)"
   puts "Saudi Arabia, Riyal (SAR)"
   puts "Scotland (United Kingdom), Pound (GBP)"
   puts "Seborga, Luigino (SPL)"
   puts "Senegal, CFA Franc BCEAO (XOF)"
   puts "Serbia, Dinar (RSD)"
   puts "Seychelles, Rupee (SCR)"
   puts "Sierra Leone, Leone (SLL)"
   puts "Silver Ounce (XAG)"
   puts "Singapore, Dollar (SGD)"
   puts "Sint Eustatius, Netherlands Antilles Guilder (ANG)"
   puts "Sint Maarten, Netherlands Antilles Guilder (ANG)"
   puts "Slovakia, Koruna (SKK)"
   puts "Slovenia, Euro (EUR)"
   puts "Solomon Islands, Dollar (SBD)"
   puts "Somalia, Shilling (SOS)"
   puts "South Africa, Rand (ZAR)"
   puts "South Georgia, United Kingdom Pound (GBP)"
   puts "South Korea, Won (KRW)"
   puts "South Sandwich Islands, United Kingdom Pound (GBP)"
   puts "Spain, Euro (EUR)"
   puts "Sri Lanka, Rupee (LKR)"
   puts "Sudan, Pound (SDG)"
   puts "Suriname, Dollar (SRD)"
   puts "Svalbard and Jan Mayen, Norway Krone (NOK)"
   puts "Swaziland, Lilangeni (SZL)"
   puts "Swaziland, South Africa Rand (ZAR)"
   puts "Sweden, Krona (SEK)"
   puts "Switzerland, Franc (CHF)"
   puts "Syria, Pound (SYP)"
   puts ""
   puts "Taiwan, New Dollar (TWD)"
   puts "Tajikistan, Somoni (TJS)"
   puts "Tajikistan, Russia Ruble (RUB)"
   puts "Tanzania, Shilling (TZS)"
   puts "Thailand, Baht (THB)"
   puts "Togo, CFA Franc BCEAO (XOF)"
   puts "Tokelau, New Zealand Dollar (NZD)"
   puts "Tonga, Pa'anga (TOP)"
   puts "Transnistria, Moldova Leu (MDL)"
   puts "Trinidad and Tobago, Dollar (TTD)"
   puts "Tunisia, Dinar (TND)"
   puts "Turkey, New Lira (TRY)"
   puts "Turkmenistan, Manat (TMM)"
   puts "Turks and Caicos Islands, United States Dollar (USD)"
   puts "Tuvalu, Australia Dollar (AUD)"
   puts "Tuvalu, Dollar (TVD)"
   puts ""
   puts "Uganda, Shilling (UGX)"
   puts "Ukraine, Hryvna (UAH)"
   puts "United Arab Emirates, Dirham (AED)"
   puts "United Kingdom, Pound (GBP)"
   puts "United States, Dollar (USD)"
   puts "Uruguay, Peso (UYU)"
   puts "Uzbekistan, Som (UZS)"
   puts ""
   puts "Vanuatu, Vatu (VUV)"
   puts "Vatican City, Euro (EUR)"
   puts "Venezuela, Bolivar Fuerte (VEF)"
   puts "Vietnam, Dong (VND)"
   puts "Virgin Islands, United States Dollar (USD)"
   puts ""
   puts "Wake Island, United States Dollar (USD)"
   puts "Wallis and Futuna Islands, Comptoirs Français du Pacifique Franc (XPF)"
   puts "West Bank, Israel New Shekel (ILS)"
   puts "West Bank, Jordan Dinar (JOD)"
   puts "Western Sahara, Morocco Dirham (MAD)"
   puts "Western Samoa (Samoa), Tala (WST)"
   puts ""
   puts "Yemen, Rial (YER)"
   puts ""
   puts "Zambia, Kwacha (ZMK)"
   puts "Zimbabwe, Dollar (ZWD)"
   puts ""


   exit
end

post_uri = "http://www.xe.com/ucc/convert.cgi" 
req = Net::HTTP.post_form(URI.parse(post_uri), {'Amount' => '1', 'From' => from, 'To' => to, 'x'=> '25', 'y'=>'18' } )
case req
when Net::HTTPSuccess, Net::HTTPRedirection
   # Ok
else 
   req.error!
end

conversion = req.body.scan(/(1 #{from} = \d+\.\d+ #{to})/);
puts conversion
